### ISSUE TITLE
Security: update package use of superagent to fix vulnerability from qs library

### ISSUE THREAD

**Issue by camsjams** [whitlockjc/path-loader#11]
There is an [advisory](https://www.sourceclear.com/registry/security/prototype-override-protection-bypass/javascript/sid-3638) for the npm package [qs](https://www.npmjs.com/package/qs) that can be solved by upgrading your dependency of [superagent](https://www.npmjs.com/package/superagent) to the latest version (currently at v3.5.2), or at the very least v2.0.0

Some [additional info from snyk](https://snyk.io/vuln/npm:qs:20170213) and the [qs github issue](https://github.com/ljharb/qs/issues/200).

Should be a simple bump as there haven't been too many changes from 5 to 6 that would break.

Path loader is a dependent or transitive dependent of several swagger related packages.

**Comment by whitlockjc** [comment]
Thanks for pointing this out.  I'll release either tonight or tomorrow.

**Comment by whitlockjc** [comment]
`json-refs@v1.0.2` fixes this.  Thanks for the report.

**Comment by camsjams** [comment]
Wonderful! Thanks!
