### ISSUE TITLE
Avoid superagent method warning

### ISSUE THREAD

**Issue by brettz9** [whitlockjc/path-loader#17]
From this code:

https://github.com/whitlockjc/path-loader/blob/937d5da875b0b0dbf91b43f20278948443d9d20e/lib/loaders/http.js#L53-L56

...there actually still is always a warning in the browser because: 

https://github.com/visionmedia/superagent/blob/ec987f6f154de764435da2f5cbd88a3a85d1fb7f/lib/client.js#L631-L635 

...contains a stub for this method.

I think the warning could be avoided by checking for `window` and `self` (as superagent does in the beginning of that same file: 

https://github.com/visionmedia/superagent/blob/ec987f6f154de764435da2f5cbd88a3a85d1fb7f/lib/client.js#L6-L13 

...and if neither is present, only then do the check to run the `buffer` method...

**Comment by whitlockjc** [comment]
Have you verified this will work?  If so, do you mind submitting a PR?
