### ISSUE TITLE
Deploy changes to npm?

### ISSUE THREAD

**Issue by isabellewithers** [whitlockjc/path-loader#34]
Would you be able to deploy the changes that have been made to the npm registry? The version that exists in the npm registry is missing any updates from the last 2 years that have been made, including security vulnerabilities (such as the older version of jQuery).

You'll likely need to bump your package version for it to be deployed.

**Comment by dchocoboo** [comment]
@whitlockjc please ?

**Comment by whitlockjc** [comment]
The project hasn't changed, that's why there are no new pushes to NPM.  But I will pull down all changes, cut a release and push a new version.

**Comment by dchocoboo** [comment]
pr : https://github.com/whitlockjc/path-loader/pull/49

**Comment by whitlockjc** [comment]
Fixed in `path-loader@1.0.11`.
