### ISSUE TITLE
Engine version change should be a major change

### ISSUE THREAD

**Issue by josantana** [whitlockjc/path-loader#51]
This repository is a nested dependency of my project. The latest version (1.0.11) added the node v14 engine as mandatory (it wasn't even defined before). My project uses node v12 and the pipeline broke due to this change. Any engine update should be done on a major, so everyone that directly depends on it could test it. Please, deprecate the latest tag and release it as a major (if node engine 14 is really necessary).

https://github.com/whitlockjc/path-loader/blob/fb7cb749ee99b326a16f3f62646450ff22f5dc5a/package.json#L70

**Comment by whitlockjc** [comment]
Fixed in `path-loader@1.0.12`.
